const CACHE_NAME = 'ae-central-command-pack-v4';
const PRECACHE = [
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/README.md",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/WALKTHROUGH.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/analytics.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/assets/app.js",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/assets/media/skydexia-logo.png",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/assets/style.css",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/backups.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/contacts.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/icon-192.png",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/icon-512.png",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/index.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/leads.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/manifest.json",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/pipeline.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/playbooks.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/quick-capture.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/routes.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/settings.html",
  "./Branching Apps/Skye-Lead-Vault-Offline-Phase2-with-Walkthrough/sw.js",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/README.md",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/about.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/assets/app.js",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/assets/app.js.bak",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/assets/media/founder.png",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/assets/media/skydexia-logo.png",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/assets/style.css",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/backup.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/contacts.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/docs.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/icon-192.png",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/icon-512.png",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/index.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/manifest.json",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/offers.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/settings.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/sw.js",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/tasks.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/templates.html",
  "./Branching Apps/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/Skye-OfferForge-SkyDexia-Offline-Upgrade-v4-WalkthroughTutorial/oforge/tutorial.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/README.md",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/app-core.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/app.css",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/contacts.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/dashboard.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/db.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/engine.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/help.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/icons/icon-192.png",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/icons/icon-512.png",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/media/skydexia-logo.png",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/ops.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/receipts.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/settings.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/vault.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/assets/walkthrough.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/contacts.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/engine.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/help.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/index.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/manifest.webmanifest",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/ops.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/receipts.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/service-worker.js",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/settings.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/vault.html",
  "./Branching Apps/Skye-Split-Engine-Offline-Money-Ops-Walkthrough/skye-split-engine-offline/walkthrough.html",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/README.txt",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/founder.png",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/icon-192.png",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/icon-512.png",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/index.html",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/logo.png",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/manifest.json",
  "./Branching Apps/SkyeBox-Command-Vault/SkyeBox-Command-Vault-v6-tutorial-walkthrough/sw.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/README.md",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/app.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/assets/founder-tyrone.png",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/assets/icon-192.png",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/assets/icon-512.png",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/assets/skyes-over-london-logo.png",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/index.html",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/manifest.webmanifest",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/_lib/googleAuth.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/_lib/jwt.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/_lib/rulesApi.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/_lib/utils.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/config.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/deployRules.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify/functions/mint.js",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/netlify.toml",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/package.json",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/styles.css",
  "./Branching Apps/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/SkyePortal-Control-Plane-Vault-Workstation-v5-tutorial/sw.js",
  "./Branching Apps/ae-service-pack-master/README.txt",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/README.txt",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/cineframe.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/combo-scenarios.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/executive-authority.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/executive-web-builds.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/index.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/roadmap.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/skye-ops-beacon.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-01-web-builds/styles.css",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/README.txt",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/accessatlas.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/checkoutforge.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/combo-scenarios.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/datapilot.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/index.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/roadmap.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/signalflow.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/styles.css",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-02-core-ops/trustlayer.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/README.txt",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/brandforge.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/combo-scenarios.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/connectbridge.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/index.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/migrateops.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/pulsewire.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/roadmap.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/styles.css",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-03-infra-lifecycle/vaultops.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/README.txt",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/combo-scenarios.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/contentengine.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/index.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/insightforge.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/launchpad.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/retainengine.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/roadmap.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/shieldstack.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-04-performance-growth/styles.css",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/README.txt",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/ai-usage-uplift.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/index.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/payment-methodology.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/recruiting-overview.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/recurring-revenue.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/roadmap.html",
  "./Branching Apps/ae-service-pack-master/ae-service-pack-section-05-contractor-economics/styles.css",
  "./Branching Apps/ae-service-pack-master/all-pages.html",
  "./Branching Apps/ae-service-pack-master/index.html",
  "./Branching Apps/ae-service-pack-master/styles.css",
  "./README.md",
  "./assets/app.js",
  "./assets/founder.webp",
  "./assets/skydexia-duo.webp",
  "./assets/skydexia-solo.webp",
  "./assets/styles.css",
  "./icon-192.png",
  "./icon-512.png",
  "./index.html",
  "./manifest.json",
  "./pages/ae-command-pack.html",
  "./pages/contact-view.html",
  "./pages/contacts.html",
  "./pages/credential-pack.html",
  "./pages/dashboard.html",
  "./pages/launcher.html",
  "./pages/notes.html",
  "./pages/ops-pack.html",
  "./pages/projects.html",
  "./pages/service-pack.html",
  "./pages/settings.html",
  "./pages/sitemap.html",
  "./pages/tutorial.html",
  "./pages/vault.html",
  "./sw.js"
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  event.respondWith(
    caches.match(req).then(cached => {
      const networkFetch = fetch(req).then(response => {
        const copy = response.clone();
        caches.open(CACHE_NAME).then(cache => cache.put(req, copy)).catch(() => {});
        return response;
      }).catch(() => cached);
      return cached || networkFetch;
    })
  );
});
